#!/bin/sh
#
# Configure PL with control.bin, which should be in the /lib/firmware directory.
#
# 2/9/2023 RK

if [ `uname -m` != 'armv7l' ]; then
	echo 'ERROR: This script must be run on a PYNQ-Z2'
	exit 1
fi

sudo sh -c 'echo control.bin >/sys/class/fpga_manager/fpga0/firmware'
